Epoch 1/10 Training:   0%|                                                                                                                                                                   | 0/2741 [00:00<?, ?it/s]/Users/tylerpoore/Workspace/projects/squad-deberta-analysis/.venv/lib/python3.11/site-packages/torch/amp/autocast_mode.py:265: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn(
Epoch 1/10 Training: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2741/2741 [2:50:57<00:00,  3.74s/it, avg_loss=0.978]
Validation Loss: 0.7837, EM: 0.6443, F1: 0.8253
Saving new best model at epoch 1
Traceback (most recent call last):
  File "/Users/tylerpoore/Workspace/projects/squad-deberta-analysis/scripts/run_experiment.py", line 46, in <module>
    main()
  File "/Users/tylerpoore/Workspace/projects/squad-deberta-analysis/scripts/run_experiment.py", line 43, in main
    train_model(model, processed_dataset, tokenizer, optimizer, scheduler, scaler, device, config)
  File "/Users/tylerpoore/Workspace/projects/squad-deberta-analysis/src/train.py", line 103, in train_model
    epoch_model_path = os.path.join(config['checkpoint_dir'], f'epoch_{epoch + 1}')
                                    ~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'checkpoint_dir'
